version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/src/:/app/src/:rw
    environment:
      - WATCHPACK_POLLING=true

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/src/:rw
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  db:
    image: postgres
    environment:
      POSTGRES_DB: good_corner_db
      POSTGRES_USER: good-corner
      POSTGRES_PASSWORD: supermdp
      PGDATA: customDataFolder
    volumes:
      - ./dbData/:/var/lib/postgresql/data/customDataFolder
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
