GET http://localhost:3000/

### GET
GET http://localhost:3000/ad

### GET By ID
GET http://localhost:3000/ad/2

### POST
POST http://localhost:3000/ad
Content-Type: application/json

{
    "title": "Bike for sell",
    "description": "My bike is green, working fine. I'm selling it because I've got a new one",
    "owner": "bike.green.seller@gmail.com",
    "price": 150,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z"
}

### PUT By ID
PUT http://localhost:3000/ad/3
Content-Type: application/json

{
    "title": "Bike sold",
    "description": "My bike is green, working fine. I'm selling it because I've got a new one",
    "owner": "bike.green.seller@gmail.com",
    "price": 150,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z"
}

### DELETE By ID
DELETE http://localhost:3000/ad/3