### GET ALL
GET http://localhost:5000/ad

### GET ALL
GET http://localhost:5000/ad?tag=voiture

### GET ALL
GET http://localhost:5000/ad?categoryId=3&tag=bike

### GET ALL
GET http://localhost:5000/ad?categoryId=2

### GET By ID
GET http://localhost:5000/ad/21

### Get Clothes
GET http://localhost:5000/ad-clothes

### Get Clothes And Cars
GET http://localhost:5000/ad-clothes-and-cars

### Get Avg from other
GET http://localhost:5000/avg-price-other

### Get Ad starting by v
GET http://localhost:5000/ad-start-by-v

### POST
POST http://localhost:5000/ad
Content-Type: application/json

{
    "title": "Bike for sell",
    "description": "My bike is green, working fine. I'm selling it because I've got a new one",
    "owner": "bike.green.seller@gmail.com",
    "price": 150,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "category_id" : 3,
    "tags": ["bike", "sell", "green"]
}

### PUT By ID
PUT http://localhost:5000/ad/1
Content-Type: application/json

{
    "title": "Bike sold",
    "description": "My bike is green, working fine. I'm selling it because I've got a new one",
    "owner": "bike.green.seller@gmail.com",
    "price": 150,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "category_id": 3,
    "tags": ["bike", "sold", "green"]
}

### DELETE By ID
DELETE http://localhost:5000/ad/21

### Get Categories
GET http://localhost:5000/categories?terms=vê

### Get Tags
GET http://localhost:5000/tags?terms=

### Delete Tags
DELETE http://localhost:5000/tags/2